import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import ThemeProvider from "@/components/ui/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-base text-text">
        <ThemeProvider
          attribute="class"
          enableSystem
          defaultTheme="system"
          value={{
            light: "latte",
            dark: "mocha",
            system: "system",
          }}
          disableTransitionOnChange
          themes={["latte", "frappe", "macchiato", "mocha"]}
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
